library(SingleCellExperiment)
library(scater)
library(stringr)
library(stats)
library(BiocParallel)
library(BiocGenerics)
library(parallel)
library(MASS)
library(nloptr)
library(Seurat)
library(edgeR)
library(singleCellHaystack)
set.seed(321)
pbmc <- readRDS("./results/pbmc3k.rds")
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
pbmc <- ScaleData(pbmc)
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
pbmc <- RunUMAP(pbmc, dims = 1:15)
haystack_umap <- haystack(pbmc,coord = "umap",method = "2D")
haystack_pca <- haystack(pbmc,coord = "pca",dims = 1:15,method = "highD")
save(haystack_pca,haystack_umap,file = "./results/pbmc_haystack.RData")

pbmc <- RunUMAP(pbmc, dims = 1:10)
haystack_umap <- haystack(pbmc,coord = "umap",method = "2D")
haystack_pca <- haystack(pbmc,coord = "pca",dims = 1:10,method = "highD")
save(haystack_pca,haystack_umap,file = "./results/pbmc_haystack_10PC.RData")