library(SingleCellExperiment)
library(scater)
library(stringr)
library(stats)
library(BiocParallel)
library(BiocGenerics)
library(parallel)
library(MASS)
library(nloptr)
library(Seurat)
library(edgeR)
library(singleCellHaystack)
set.seed(321)
ifnb <- readRDS("./results/ifnb_ctrl.rds")
ifnb <- FindVariableFeatures(ifnb, selection.method = "vst", nfeatures = 2000)
ifnb <- ScaleData(ifnb)
ifnb <- RunPCA(ifnb, features = VariableFeatures(object = ifnb))
ifnb <- RunTSNE(ifnb, dims = 1:25)
haystack_umap <- haystack(ifnb,coord = "tsne",method = "2D")
haystack_pca <- haystack(ifnb,coord = "pca",dims = 1:25,method = "highD")
save(haystack_pca,haystack_umap,file = "./results/ifnb_haystack.RData")

ifnb <- RunTSNE(ifnb, dims = 1:20)
haystack_umap <- haystack(ifnb,coord = "tsne",method = "2D")
haystack_pca <- haystack(ifnb,coord = "pca",dims = 1:20,method = "highD")
save(haystack_pca,haystack_umap,file = "./results/ifnb_haystack_20PC.RData")